### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by dodoburner** [Alfred-KInyua/Leaderboard-setup-project#4]
Hey Alfred good job, I like how you done your modules they are very clear and with no extra stuff in them. I have a few recommendations though.

- You can use required to check if the user has filled both of the inputs for submitting the score or make a custom error message so the user can see what he did wrong. It is more user friendly
- I suggest to name your export default functions the same as the module files they are from so it is easier to look them up
- The leaderboard doesn't display the scores from the top down
- The print.js is empty

**Comment by Alfred-KInyua** [comment]
Fixed all issues, 
https://github.com/Alfred-KInyua/Leaderboard-setup-project/pull/3  Click the provided link to see
